/**
 * Table de correspondance Spécialités → codes NOS (TRE-R38-SpecialiteOrdinale)
 * Source: https://interop.esante.gouv.fr/ig/nos/CodeSystem-TRE-R38-SpecialiteOrdinale.html
 * Utilisé pour la recherche via qualification-code sur l'API FHIR
 */
const SPECIALTIES = [
  { label: "Allergologie", code: "SM57" },
  { label: "Anatomie et Cytologie pathologiques", code: "SM01" },
  { label: "Anesthésie-réanimation", code: "SM02" },
  { label: "Biologie médicale", code: "SM03" },
  { label: "Cardiologie et Maladies vasculaires", code: "SM04" },
  { label: "Chirurgie générale", code: "SM05" },
  { label: "Chirurgie infantile", code: "SM09" },
  { label: "Chirurgie maxillo-faciale", code: "SM06" },
  { label: "Chirurgie maxillo-faciale et Stomatologie", code: "SM07" },
  { label: "Chirurgie orale", code: "SM56" },
  { label: "Chirurgie orthopédique et Traumatologie", code: "SM08" },
  { label: "Chirurgie plastique reconstructrice et esthétique", code: "SM10" },
  { label: "Chirurgie thoracique et cardio-vasculaire", code: "SM11" },
  { label: "Chirurgie urologique", code: "SM12" },
  { label: "Chirurgie vasculaire", code: "SM13" },
  { label: "Chirurgie viscérale et digestive", code: "SM14" },
  { label: "Dermatologie et Vénéréologie", code: "SM15" },
  { label: "Endocrinologie et Métabolisme", code: "SM16" },
  { label: "Endocrinologie, diabétologie, nutrition", code: "SM62" },
  { label: "Gastro-entérologie et Hépatologie", code: "SM24" },
  { label: "Génétique médicale", code: "SM17" },
  { label: "Gériatrie", code: "SM18" },
  { label: "Gynécologie médicale", code: "SM19" },
  { label: "Gynécologie-obstétrique", code: "SM20" },
  { label: "Hématologie", code: "SM21" },
  { label: "Maladies infectieuses et tropicales", code: "SM58" },
  { label: "Médecine cardiovasculaire", code: "SM73" },
  { label: "Médecine d'urgence", code: "SM59" },
  { label: "Médecine du travail", code: "SM25" },
  { label: "Médecine générale", code: "SM54" },
  { label: "Médecine intensive-réanimation", code: "SM46" },
  { label: "Médecine interne", code: "SM27" },
  { label: "Médecine interne et immunologie clinique", code: "SM72" },
  { label: "Médecine légale et expertises médicales", code: "SM60" },
  { label: "Médecine nucléaire", code: "SM28" },
  { label: "Médecine physique et de réadaptation", code: "SM29" },
  { label: "Médecine vasculaire", code: "SM61" },
  { label: "Néphrologie", code: "SM30" },
  { label: "Neuro-chirurgie", code: "SM31" },
  { label: "Neurologie", code: "SM32" },
  { label: "ORL et Chirurgie cervico-faciale", code: "SM34" },
  { label: "Oncologie, option médicale", code: "SM36" },
  { label: "Oncologie, option radiothérapie", code: "SM37" },
  { label: "Ophtalmologie", code: "SM38" },
  { label: "Orthopédie dento-faciale", code: "SCD01" },
  { label: "Oto-rhino-laryngologie", code: "SM39" },
  { label: "Pédiatrie", code: "SM40" },
  { label: "Pneumologie", code: "SM41" },
  { label: "Psychiatrie", code: "SM42" },
  { label: "Psychiatrie, option enfant et adolescent", code: "SM43" },
  { label: "Radiologie et imagerie médicale", code: "SM74" },
  { label: "Radio-diagnostic", code: "SM44" },
  { label: "Radio-thérapie", code: "SM45" },
  { label: "Rhumatologie", code: "SM48" },
  { label: "Santé publique", code: "SM75" },
  { label: "Santé publique et Médecine sociale", code: "SM49" },
  { label: "Stomatologie", code: "SM50" },
  { label: "Médecine bucco-dentaire", code: "SCD03" },
];
